---
title: " spatial data for covid 19 CONFIRMED CASES ON 03 september 2021 in Rwanda"
author: "Emmanuel Sindikubwabo"
date: "9/4/2021"
output: html_document
---

```{r }
#Helper libraries
library(ggmap)
library(scales)
library(maptools)
library(raster)
library(plyr)
library(ggplot2)
library(rgdal)
library(ggiraph)
library(hrbrthemes)

Rwanda1<-getData("GADM", country="RW", level=1)

 plot(Rwanda1, main = "County Boundaries in Rwanda")
 
```


```{r }
#UTM(Universal Transverse Mercator) for prorownames
Rwanda1_UTM <-spTransform(Rwanda1, CRS("+init=EPSG:32737")) 

Rwanda1_UTM@data$VARNAME_1

```


# readind data from hard disk
```{r}
confirmed.cases <- read.csv("D:\\1.DATA SCIENCEMasters\\SemesterII\\4. Advanceddatamining\\COUNTY DATA.csv", header=TRUE)
confirmed.cases
```


# This Graph represents the real data for covid 19 CONFIRMED CASES ON 03 september 2021 in Rwanda.
# Data were accessed from Rwanda website(www.rbc.gov.rw)
####link:https://www.rbc.gov.rw/fileadmin/user_upload/annoucement/new%20cases%20per%20district%2003%2009%202021.jpg
```{r}
  
count_df<-data.frame(confirmed.cases[1:5,])
attach(count_df)
Rwanda1_UTM@data$id <- rownames(Rwanda1_UTM@data)
Rwanda1_UTM@data <- join(Rwanda1_UTM@data, count_df, by="NAME_1")
Rwanda1_df <- fortify(Rwanda1_UTM)
Rwanda1_df <- join(Rwanda1_df,Rwanda1_UTM@data, by="id")
Rwanda1_df

```
```{r}
library(ggiraph)
ggplot() + 
  geom_polygon(data = Rwanda1_df, aes(x = long, y = lat, group = group, fill =
                                         Count), color = "purple", size = 0.25) +
  theme(aspect.ratio=0.8)+
  scale_fill_distiller(name="Confirmed Cases", palette ="Spectral", breaks = pretty_breaks(n = 5))+
  labs(title="COVID-19 CONFIRMED CUMULATIVE CASES IN THE REGIONS")
```



```{r}
library(tmap)
library(tmaptools)

#COVID-19 Confirmed Cases Plotting with respective regions
tmap_mode('view')
tm_shape(Rwanda1_UTM) +
  tm_polygons("Count",id="NAME_1")
tmap_last()
```

